-- Drop existing tables to start fresh (optional)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE holdings';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE portfolios';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE teams';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Create tables
CREATE TABLE teams (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    played NUMBER DEFAULT 0,
    won NUMBER DEFAULT 0,
    drawn NUMBER DEFAULT 0,
    lost NUMBER DEFAULT 0,
    points NUMBER DEFAULT 0,
    price NUMBER(10, 2) DEFAULT 100.00,
    PRIMARY KEY(id)
);

CREATE TABLE portfolios (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cash NUMBER(10, 2) DEFAULT 10000.00,
    PRIMARY KEY(user_id)
);

CREATE TABLE holdings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER,
    team_id NUMBER,
    shares NUMBER,
    PRIMARY KEY(id),
    FOREIGN KEY(user_id) REFERENCES portfolios(user_id),
    FOREIGN KEY(team_id) REFERENCES teams(id)
);

-- Insert sample data
INSERT INTO teams (name, played, won, drawn, lost, points, price) VALUES ('Real Madrid', 5, 5, 0, 0, 15, 150.00);
INSERT INTO teams (name, played, won, drawn, lost, points, price) VALUES ('FC Barcelona', 5, 4, 1, 0, 13, 140.00);
INSERT INTO teams (name, played, won, drawn, lost, points, price) VALUES ('Atletico Madrid', 5, 3, 1, 1, 10, 120.00);
INSERT INTO teams (name, played, won, drawn, lost, points, price) VALUES ('Sevilla FC', 5, 2, 2, 1, 8, 110.00);
INSERT INTO teams (name, played, won, drawn, lost, points, price) VALUES ('Real Betis', 5, 1, 2, 2, 5, 90.00);

-- Create a sample user portfolio
INSERT INTO portfolios (user_id, cash) VALUES (1, 1000.00);

-- Give the user some holdings
INSERT INTO holdings (user_id, team_id, shares) VALUES (1, 1, 10); -- 10 shares of Real Madrid
INSERT INTO holdings (user_id, team_id, shares) VALUES (1, 3, 5);  -- 5 shares of Atletico Madrid

COMMIT;

-- Verify the data
SELECT * FROM teams;
SELECT * FROM portfolios;
SELECT * FROM holdings;
